"""sources

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 14:14:16.745664
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('telegram', 'website', 'rss', 'instagram', name='source_kind'), nullable=False),
    sa.Column('key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('new', 'ok', 'error', 'unavailable', name='source_status'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_sources')),
    sa.UniqueConstraint('kind', 'key', name='uq_global_sources_kind_key')
    )
    op.create_table('global_posts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('global_source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('canonical_url', sa.String(length=1000), nullable=True),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metrics_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['global_source_id'], ['global_sources.id'], name=op.f('fk_global_posts_global_source_id_global_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_posts')),
    sa.UniqueConstraint('global_source_id', 'external_id', name='uq_global_posts_source_ext')
    )
    op.create_index(op.f('ix_global_posts_canonical_url'), 'global_posts', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_global_posts_content_hash'), 'global_posts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_global_posts_global_source_id'), 'global_posts', ['global_source_id'], unique=False)
    op.create_index(op.f('ix_global_posts_published_at'), 'global_posts', ['published_at'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('global_source_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('own', 'competitor', 'market', name='source_role'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_sources_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['global_source_id'], ['global_sources.id'], name=op.f('fk_sources_global_source_id_global_sources'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sources_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('organization_id', 'global_source_id', name='uq_sources_org_global')
    )
    op.create_index(op.f('ix_sources_global_source_id'), 'sources', ['global_source_id'], unique=False)
    op.create_index(op.f('ix_sources_organization_id'), 'sources', ['organization_id'], unique=False)
    op.create_table('post_metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['global_posts.id'], name=op.f('fk_post_metrics_post_id_global_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_metrics'))
    )
    op.create_index(op.f('ix_post_metrics_post_id'), 'post_metrics', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_metrics_post_id'), table_name='post_metrics')
    op.drop_table('post_metrics')
    op.drop_index(op.f('ix_sources_organization_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_global_source_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_global_posts_published_at'), table_name='global_posts')
    op.drop_index(op.f('ix_global_posts_global_source_id'), table_name='global_posts')
    op.drop_index(op.f('ix_global_posts_content_hash'), table_name='global_posts')
    op.drop_index(op.f('ix_global_posts_canonical_url'), table_name='global_posts')
    op.drop_table('global_posts')
    op.drop_table('global_sources')
    # ### end Alembic commands ###
    for name in ('source_role', 'source_status', 'source_kind'):
        sa.Enum(name=name).drop(op.get_bind(), checkfirst=True)
