"""market intelligence

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 15:32:58.598522
"""
from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxonomies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('roles', sa.JSON(), nullable=False),
    sa.Column('niche', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_taxonomies_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taxonomies')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_taxonomies_organization_id'))
    )
    op.create_table('post_analysis',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('taxonomy_version', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=40), nullable=True),
    sa.Column('funnel_stage', sa.String(length=40), nullable=True),
    sa.Column('hook_type', sa.String(length=40), nullable=True),
    sa.Column('cta_type', sa.String(length=40), nullable=True),
    sa.Column('proof_type', sa.String(length=40), nullable=True),
    sa.Column('tone', sa.String(length=40), nullable=True),
    sa.Column('value_type', sa.String(length=40), nullable=True),
    sa.Column('topic', sa.String(length=120), nullable=True),
    sa.Column('target_role', sa.String(length=120), nullable=True),
    sa.Column('has_case', sa.Boolean(), nullable=True),
    sa.Column('has_numbers', sa.Boolean(), nullable=True),
    sa.Column('has_offer', sa.Boolean(), nullable=True),
    sa.Column('has_lead_magnet', sa.Boolean(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_post_analysis_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['global_posts.id'], name=op.f('fk_post_analysis_post_id_global_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_analysis')),
    sa.UniqueConstraint('organization_id', 'post_id', name='uq_post_analysis_org_post')
    )
    op.create_index(op.f('ix_post_analysis_organization_id'), 'post_analysis', ['organization_id'], unique=False)
    op.create_index(op.f('ix_post_analysis_post_id'), 'post_analysis', ['post_id'], unique=False)
    op.create_index(op.f('ix_post_analysis_topic'), 'post_analysis', ['topic'], unique=False)
    op.create_table('post_embeddings',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['global_posts.id'], name=op.f('fk_post_embeddings_post_id_global_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', name=op.f('pk_post_embeddings'))
    )
    op.create_index('ix_post_embeddings_hnsw', 'post_embeddings', ['embedding'], unique=False,
                    postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.add_column('global_posts', sa.Column('engagement', sa.BigInteger(), nullable=True))
    op.add_column('global_posts', sa.Column('er', sa.Float(), nullable=True))
    op.add_column('global_posts', sa.Column('overperformance', sa.Float(), nullable=True))
    op.add_column('global_posts', sa.Column('duplicate_of_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(op.f('fk_global_posts_duplicate_of_id_global_posts'), 'global_posts', 'global_posts', ['duplicate_of_id'], ['id'], ondelete='SET NULL')
    op.add_column('global_sources', sa.Column('median_views', sa.Float(), nullable=True))
    op.add_column('global_sources', sa.Column('median_engagement', sa.Float(), nullable=True))
    op.add_column('global_sources', sa.Column('metrics_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_sources', 'metrics_at')
    op.drop_column('global_sources', 'median_engagement')
    op.drop_column('global_sources', 'median_views')
    op.drop_constraint(op.f('fk_global_posts_duplicate_of_id_global_posts'), 'global_posts', type_='foreignkey')
    op.drop_column('global_posts', 'duplicate_of_id')
    op.drop_column('global_posts', 'overperformance')
    op.drop_column('global_posts', 'er')
    op.drop_column('global_posts', 'engagement')
    op.drop_index('ix_post_embeddings_hnsw', table_name='post_embeddings',
                  postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('post_embeddings')
    op.drop_index(op.f('ix_post_analysis_topic'), table_name='post_analysis')
    op.drop_index(op.f('ix_post_analysis_post_id'), table_name='post_analysis')
    op.drop_index(op.f('ix_post_analysis_organization_id'), table_name='post_analysis')
    op.drop_table('post_analysis')
    op.drop_table('taxonomies')
    # ### end Alembic commands ###
