"""competitors

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-26 15:49:25.947733
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE source_kind ADD VALUE IF NOT EXISTS 'youtube'")
        op.execute("ALTER TYPE source_kind ADD VALUE IF NOT EXISTS 'vk'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('profile_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_model', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_competitors_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_competitors_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitors')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_competitors_org_name')
    )
    op.create_index(op.f('ix_competitors_organization_id'), 'competitors', ['organization_id'], unique=False)
    op.add_column('sources', sa.Column('competitor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sources_competitor_id'), 'sources', ['competitor_id'], unique=False)
    op.create_foreign_key(op.f('fk_sources_competitor_id_competitors'), 'sources', 'competitors', ['competitor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_sources_competitor_id_competitors'), 'sources', type_='foreignkey')
    op.drop_index(op.f('ix_sources_competitor_id'), table_name='sources')
    op.drop_column('sources', 'competitor_id')
    op.drop_index(op.f('ix_competitors_organization_id'), table_name='competitors')
    op.drop_table('competitors')
    # ### end Alembic commands ###
    # PostgreSQL не удаляет значения enum — пересоздаём тип без youtube/vk
    op.execute("DELETE FROM sources WHERE global_source_id IN "
               "(SELECT id FROM global_sources WHERE kind IN ('youtube', 'vk'))")
    op.execute("DELETE FROM global_sources WHERE kind IN ('youtube', 'vk')")
    op.execute("ALTER TYPE source_kind RENAME TO source_kind_old")
    op.execute("CREATE TYPE source_kind AS ENUM ('telegram', 'website', 'rss', 'instagram')")
    op.execute("ALTER TABLE global_sources ALTER COLUMN kind TYPE source_kind USING kind::text::source_kind")
    op.execute("DROP TYPE source_kind_old")
