"""post insights

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-26 16:02:33.921480
"""
from alembic import op
import sqlalchemy as sa


revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_insights',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_post_insights_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['global_posts.id'], name=op.f('fk_post_insights_post_id_global_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_insights')),
    sa.UniqueConstraint('organization_id', 'post_id', name='uq_post_insights_org_post')
    )
    op.create_index(op.f('ix_post_insights_organization_id'), 'post_insights', ['organization_id'], unique=False)
    op.create_index(op.f('ix_post_insights_post_id'), 'post_insights', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_insights_post_id'), table_name='post_insights')
    op.drop_index(op.f('ix_post_insights_organization_id'), table_name='post_insights')
    op.drop_table('post_insights')
    # ### end Alembic commands ###
