"""topics

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-26 16:22:28.121834
"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_topic_insights_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_insights')),
    sa.UniqueConstraint('organization_id', 'topic', name='uq_topic_insights_org_topic')
    )
    op.create_index(op.f('ix_topic_insights_organization_id'), 'topic_insights', ['organization_id'], unique=False)
    op.create_table('topic_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_topic_clusters_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_topic_clusters_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_clusters'))
    )
    op.create_index(op.f('ix_topic_clusters_organization_id'), 'topic_clusters', ['organization_id'], unique=False)
    op.create_index(op.f('ix_topic_clusters_topic'), 'topic_clusters', ['topic'], unique=False)
    op.create_table('topic_cluster_posts',
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['topic_clusters.id'], name=op.f('fk_topic_cluster_posts_cluster_id_topic_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['global_posts.id'], name=op.f('fk_topic_cluster_posts_post_id_global_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cluster_id', 'post_id', name=op.f('pk_topic_cluster_posts'))
    )
    op.create_index(op.f('ix_topic_cluster_posts_post_id'), 'topic_cluster_posts', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_cluster_posts_post_id'), table_name='topic_cluster_posts')
    op.drop_table('topic_cluster_posts')
    op.drop_index(op.f('ix_topic_clusters_topic'), table_name='topic_clusters')
    op.drop_index(op.f('ix_topic_clusters_organization_id'), table_name='topic_clusters')
    op.drop_table('topic_clusters')
    op.drop_index(op.f('ix_topic_insights_organization_id'), table_name='topic_insights')
    op.drop_table('topic_insights')
    # ### end Alembic commands ###
