"""websites

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-26 16:45:35.321444
"""
from alembic import op
import sqlalchemy as sa


revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_websites_competitor_id_competitors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_websites_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_websites_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_websites')),
    sa.UniqueConstraint('organization_id', 'url', name='uq_websites_org_url')
    )
    op.create_index(op.f('ix_websites_competitor_id'), 'websites', ['competitor_id'], unique=False)
    op.create_index(op.f('ix_websites_organization_id'), 'websites', ['organization_id'], unique=False)
    op.create_table('website_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('tracked', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('last_hash', sa.String(length=64), nullable=True),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_website_pages_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_website_pages')),
    sa.UniqueConstraint('website_id', 'url', name='uq_website_pages_site_url')
    )
    op.create_index(op.f('ix_website_pages_website_id'), 'website_pages', ['website_id'], unique=False)
    op.create_table('page_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['website_pages.id'], name=op.f('fk_page_snapshots_page_id_website_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_snapshots'))
    )
    op.create_index(op.f('ix_page_snapshots_page_id'), 'page_snapshots', ['page_id'], unique=False)
    op.create_table('website_changes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('added', sa.JSON(), nullable=False),
    sa.Column('removed', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('importance', sa.String(length=10), nullable=True),
    sa.Column('ai', sa.Boolean(), nullable=False),
    sa.Column('before_snapshot_id', sa.BigInteger(), nullable=True),
    sa.Column('after_snapshot_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['after_snapshot_id'], ['page_snapshots.id'], name=op.f('fk_website_changes_after_snapshot_id_page_snapshots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['before_snapshot_id'], ['page_snapshots.id'], name=op.f('fk_website_changes_before_snapshot_id_page_snapshots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['website_pages.id'], name=op.f('fk_website_changes_page_id_website_pages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], name=op.f('fk_website_changes_website_id_websites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_website_changes'))
    )
    op.create_index(op.f('ix_website_changes_detected_at'), 'website_changes', ['detected_at'], unique=False)
    op.create_index(op.f('ix_website_changes_page_id'), 'website_changes', ['page_id'], unique=False)
    op.create_index(op.f('ix_website_changes_website_id'), 'website_changes', ['website_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_changes_website_id'), table_name='website_changes')
    op.drop_index(op.f('ix_website_changes_page_id'), table_name='website_changes')
    op.drop_index(op.f('ix_website_changes_detected_at'), table_name='website_changes')
    op.drop_table('website_changes')
    op.drop_index(op.f('ix_page_snapshots_page_id'), table_name='page_snapshots')
    op.drop_table('page_snapshots')
    op.drop_index(op.f('ix_website_pages_website_id'), table_name='website_pages')
    op.drop_table('website_pages')
    op.drop_index(op.f('ix_websites_organization_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_competitor_id'), table_name='websites')
    op.drop_table('websites')
    # ### end Alembic commands ###
