"""audits

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-26 17:21:30.992093
"""
from alembic import op
import sqlalchemy as sa


revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=1000), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('use_own_sources', sa.Boolean(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('public_token', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_content_audits_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_content_audits_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_content_audits_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_audits')),
    sa.UniqueConstraint('public_token', name=op.f('uq_content_audits_public_token'))
    )
    op.create_index(op.f('ix_content_audits_email'), 'content_audits', ['email'], unique=False)
    op.create_index(op.f('ix_content_audits_ip_hash'), 'content_audits', ['ip_hash'], unique=False)
    op.create_index(op.f('ix_content_audits_organization_id'), 'content_audits', ['organization_id'], unique=False)
    op.create_table('audit_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('criterion', sa.String(length=40), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('ai', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['content_audits.id'], name=op.f('fk_audit_items_audit_id_content_audits'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_items'))
    )
    op.create_index(op.f('ix_audit_items_audit_id'), 'audit_items', ['audit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_items_audit_id'), table_name='audit_items')
    op.drop_table('audit_items')
    op.drop_index(op.f('ix_content_audits_organization_id'), table_name='content_audits')
    op.drop_index(op.f('ix_content_audits_ip_hash'), table_name='content_audits')
    op.drop_index(op.f('ix_content_audits_email'), table_name='content_audits')
    op.drop_table('content_audits')
    # ### end Alembic commands ###
