"""strategy

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-26 17:43:19.439669
"""
from alembic import op
import sqlalchemy as sa


revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('audit_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=True),
    sa.Column('why', sa.Text(), nullable=False),
    sa.Column('angle', sa.Text(), nullable=False),
    sa.Column('formats', sa.JSON(), nullable=False),
    sa.Column('funnel_stage', sa.String(length=40), nullable=True),
    sa.Column('target_role', sa.String(length=120), nullable=True),
    sa.Column('fixes', sa.JSON(), nullable=False),
    sa.Column('market', sa.JSON(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('ai', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['content_audits.id'], name=op.f('fk_content_opportunities_audit_id_content_audits'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_content_opportunities_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_content_opportunities_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_opportunities'))
    )
    op.create_index(op.f('ix_content_opportunities_organization_id'), 'content_opportunities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_content_opportunities_status'), 'content_opportunities', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_opportunities_status'), table_name='content_opportunities')
    op.drop_index(op.f('ix_content_opportunities_organization_id'), table_name='content_opportunities')
    op.drop_table('content_opportunities')
    # ### end Alembic commands ###
