"""factory

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-26 17:58:09.978865
"""
from alembic import op
import sqlalchemy as sa


revision = '0010'
down_revision = '0009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=1000), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('offer', sa.Text(), nullable=True),
    sa.Column('audience', sa.Text(), nullable=True),
    sa.Column('differentiators', sa.JSON(), nullable=False),
    sa.Column('proof_points', sa.JSON(), nullable=False),
    sa.Column('cta', sa.Text(), nullable=True),
    sa.Column('tone', sa.Text(), nullable=True),
    sa.Column('do', sa.JSON(), nullable=False),
    sa.Column('dont', sa.JSON(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_brand_profiles_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_profiles')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_brand_profiles_organization_id'))
    )
    op.create_table('content_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('brief', sa.Text(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_content_projects_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['content_opportunities.id'], name=op.f('fk_content_projects_opportunity_id_content_opportunities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_content_projects_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_projects'))
    )
    op.create_index(op.f('ix_content_projects_organization_id'), 'content_projects', ['organization_id'], unique=False)
    op.create_table('content_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('fields', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('qa', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_content_versions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['content_projects.id'], name=op.f('fk_content_versions_project_id_content_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_versions')),
    sa.UniqueConstraint('project_id', 'number', name='uq_content_versions_project_number')
    )
    op.create_index(op.f('ix_content_versions_project_id'), 'content_versions', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_versions_project_id'), table_name='content_versions')
    op.drop_table('content_versions')
    op.drop_index(op.f('ix_content_projects_organization_id'), table_name='content_projects')
    op.drop_table('content_projects')
    op.drop_table('brand_profiles')
    # ### end Alembic commands ###
