"""digests

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-26 18:12:44.161306
"""
from alembic import op
import sqlalchemy as sa


revision = '0011'
down_revision = '0010'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digest_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('every_days', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('send_email', sa.Boolean(), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_digest_schedules_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_digest_schedules')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_digest_schedules_organization_id'))
    )
    op.create_index(op.f('ix_digest_schedules_next_run_at'), 'digest_schedules', ['next_run_at'], unique=False)
    op.create_table('digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('period_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('ai', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_digests_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_digests_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_digests'))
    )
    op.create_index(op.f('ix_digests_organization_id'), 'digests', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_digests_organization_id'), table_name='digests')
    op.drop_table('digests')
    op.drop_index(op.f('ix_digest_schedules_next_run_at'), table_name='digest_schedules')
    op.drop_table('digest_schedules')
    # ### end Alembic commands ###
