"""admin

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-26 18:24:05.626797
"""
from alembic import op
import sqlalchemy as sa


revision = '0012'
down_revision = '0011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], name=op.f('fk_admin_actions_admin_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_admin_actions_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_actions'))
    )
    op.create_index(op.f('ix_admin_actions_at'), 'admin_actions', ['at'], unique=False)
    op.create_index(op.f('ix_admin_actions_organization_id'), 'admin_actions', ['organization_id'], unique=False)
    op.add_column('subscriptions', sa.Column('limits_override', sa.JSON(), nullable=True))
    op.add_column('subscriptions', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen_at')
    op.drop_column('subscriptions', 'note')
    op.drop_column('subscriptions', 'limits_override')
    op.drop_index(op.f('ix_admin_actions_organization_id'), table_name='admin_actions')
    op.drop_index(op.f('ix_admin_actions_at'), table_name='admin_actions')
    op.drop_table('admin_actions')
    # ### end Alembic commands ###
